# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 42389848eaf7e2cbb9f10d47b74b742086d4570490c32a410aa4dfb227e9d97b7a69b05ca377b5ff4edecd446349e3064d0658785266fcb5efa5d9a7c74a7212

test:
  secret_key_base: 204a41307b951664901242afe6d3f438a039eba3230841fcb0ce0a3cd30b45ba94eaadcbbe5b53fa1bb33ad4bbdfb4e2ea88324d2c34b46135f94ed43ce4abce

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
